service:
  name: form2email

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  profile: crawlity-serverless-admin

functions:
  submitForm:
    handler: src/aws/handler.submitForm
    events:
      - http:
          method: post
          path: forms
